import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/Footer";
import { Providers } from "@/app/Providers";
import { Toaster } from "@/components/ui/sonner";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-blue-20`}>
        <Providers>
          <Header />
          <main className="container">
            <div className="content pt-3">
              {children}

              <Toaster />
            </div>
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
