import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/Footer";
import Breadcrumb from "@/components/breadcrumb/page";
import { ToastContainer, toast } from "react-toastify";
import { TooltipProvider } from "@/components/ui/tooltip";
import { ProductProvider } from "./context/productContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-blue-20`}>
        <ProductProvider>
          <ToastContainer />
          <Header />
          <main className="container">
            <div className="content pt-3  ">
              <Breadcrumb />
              <TooltipProvider>{children}</TooltipProvider>
            </div>
          </main>
          <Footer />
        </ProductProvider>
      </body>
    </html>
  );
}
